export const STATIC_PAGES = [
    { name: 'Home', path: '/' },
    { name: 'About Us', path: '/about' },
    { name: 'Admission', path: '/admission' },
    { name: 'Affiliation', path: '/affiliation' },
    { name: 'Blog', path: '/blog' },
    { name: 'Contact Us', path: '/contact' },
    { name: 'Courses', path: '/courses' },
    { name: 'Degree Courses', path: '/courses/degree' },
    { name: 'Diploma Courses', path: '/courses/diploma' },
    { name: 'Hotel Management', path: '/courses/hotel-management' },
    { name: 'Paramedical', path: '/courses/paramedical' },
    { name: 'Facilities', path: '/facilities' },
    { name: 'Gallery', path: '/gallery' },
    { name: 'Placements', path: '/placements' },
    { name: 'Privacy Policy', path: '/privacy-policy' },
    { name: 'Register', path: '/register' },
    { name: 'Scholarship', path: '/scholarship' },
    { name: 'Student Testimonials', path: '/student-testimonials' },
];
