import PageBreadcrumb from '@/components/PageBreadcrumb';
import Link from 'next/link';

export default function PrivacyPolicy() {
    return (
        <>
            <PageBreadcrumb
                title="Privacy Policy"
                bgImage="/images/background/contactbanner-new3.jpg"
                breadcrumbs={[
                    { label: 'Home', url: '/' },
                    { label: 'Privacy Policy' }
                ]}
            />

            <section className="default-section sec-padd6 contact_page">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12">
                            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>

                            <h3>Interpretation and Definitions</h3>
                            <h4>Interpretation</h4>
                            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                            <h4>Definitions</h4>
                            <p>For the purposes of this Privacy Policy:</p>
                            <p><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</p>
                            <p><b>Affiliate</b> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                            <p><b>Company</b> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Bharathi Institute, Thambu chetty Strret, Brodway, Chennai.</p>
                            <p><b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                            <p><b>Country</b> refers to: Tamil Nadu, India</p>
                            <p><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                            <p><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</p>
                            <p><b>Service</b> refers to the Website.</p>
                            <p><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                            <p><b>Third-party Social Media Service</b> refers to any website or any social network website through which a User can log in or create an account to use the Service.</p>
                            <p><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                            <p><b>Website</b> refers to Bharathi Institute, accessible from https://bharathiinstitutes.com/</p>
                            <p><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>

                            <h3>Collecting and Using Your Personal Data</h3>
                            <h4>Types of Data Collected</h4>
                            <h5>Personal Data</h5>
                            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                            <ul>
                                <li>Email address</li>
                                <li>First name and last name</li>
                                <li>Phone number</li>
                                <li>Address, State, Province, ZIP/Postal code, City</li>
                                <li>Usage Data</li>
                            </ul>

                            <h5>Usage Data</h5>
                            <p>Usage Data is collected automatically when using the Service.</p>
                            <p>Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

                            <h5>Information from Third-Party Social Media Services</h5>
                            <p>The Company allows You to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
                            <ul>
                                <li>Google</li>
                                <li>Facebook</li>
                                <li>Instagram</li>
                                <li>Twitter</li>
                                <li>LinkedIn</li>
                            </ul>
                            <p>If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We may collect Personal data that is already associated with Your Third-Party Social Media Service&apos;s account, such as Your name, Your email address, Your activities or Your contact list associated with that account.</p>
                            <p>You may also have the option of sharing additional information with the Company through Your Third-Party Social Media Service&apos;s account. If You choose to provide such information and Personal Data, during registration or otherwise, You are giving the Company permission to use, share, and store it in a manner consistent with this Privacy Policy.</p>

                            <h5>Tracking Technologies and Cookies</h5>
                            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
                            <ul>
                                <li><b>Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                                <li><b>Web Beacons.</b> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
                            </ul>
                            <p>Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>

                            <h4>Use of Your Personal Data</h4>
                            <p>The Company may use Personal Data for the following purposes:</p>
                            <p><b>To provide and maintain our Service,</b> including to monitor the usage of our Service.</p>
                            <p><b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
                            <p><b>For the performance of a contract:</b> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
                            <p><b>To contact You:</b> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
                            <p><b>To provide You</b> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>
                            <p><b>To manage Your requests:</b> To attend and manage Your requests to Us.</p>

                            <h4>retention of Your Personal Data</h4>
                            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

                            <h4>Transfer of Your Personal Data</h4>
                            <p>Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located.</p>

                            <h4>Delete Your Personal Data</h4>
                            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
                            <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>

                            <h4>Disclosure of Your Personal Data</h4>
                            <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>

                            <h4>Security of Your Personal Data</h4>
                            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>

                            <h3>Contact Us</h3>
                            <p>If you have any questions about this Privacy Policy, You can contact us: <br />
                                • By phone number: 9444320052
                            </p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}
